/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConditionsDUtilisationRouteImport } from './routes/conditions-d-utilisation'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsDUtilisationRoute = ConditionsDUtilisationRouteImport.update({
  id: '/conditions-d-utilisation',
  path: '/conditions-d-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions-d-utilisation': typeof ConditionsDUtilisationRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions-d-utilisation': typeof ConditionsDUtilisationRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions-d-utilisation': typeof ConditionsDUtilisationRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conditions-d-utilisation' | '/politique-de-confidentialite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conditions-d-utilisation' | '/politique-de-confidentialite'
  id:
    | '__root__'
    | '/'
    | '/conditions-d-utilisation'
    | '/politique-de-confidentialite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsDUtilisationRoute: typeof ConditionsDUtilisationRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-d-utilisation': {
      id: '/conditions-d-utilisation'
      path: '/conditions-d-utilisation'
      fullPath: '/conditions-d-utilisation'
      preLoaderRoute: typeof ConditionsDUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsDUtilisationRoute: ConditionsDUtilisationRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
